### ISSUE TITLE
请问这个报错如何解决

### ISSUE THREAD

**Issue by Sqy000222** [cat-bucket/cat-osint#6]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/SMSBoom/smsboom.py", line 5, in <module>
    from utils.log import logger
  File "/data/data/com.termux/files/home/SMSBoom/utils/log.py", line 3, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

**Comment by cat-bucket** [comment]
原仓库已经报废了，不要弄别的，按照我的指令来不会报错

**Comment by Sqy000222** [comment]
source <(curl -L https://raw.githubusercontent.com/cat-bucket/cat-osint/main/sms.txt)

直接粘贴代码进入即可，后续可以直接使用下列指令（不要更新接口）

cd SMSBoom;python smsboom.py run -t 64 -p 184****9269 -f 60 将手机号替换为你需要轰炸的手机号
我按照这2段操作 就报错了= = 不知为何。
